name: Build Workflow

on:
  push:
    branches: main

jobs:
  build-windows_x64:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller resolution-script.spec
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows_ResolutionScript
          path: dist/resolution-script-x64.exe
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/resolution-script-x64.exe
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

  build-windows_x86:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: 'x86'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller resolution-script.spec
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows_ResolutionScript
          path: dist/resolution-script-x86.exe
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/resolution-script-x86.exe
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
